name: Build and Save Docker Image

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app
        run: npm run build
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to acr
      run: docker login testdavy.azurecr.io -u testdavy -p ${{ secrets.PSS }}

    - name: Build Docker image
      run: docker build -t webimage:v1 .
      
    - name: Push Docker image
      run: |
        docker tag webimage:v1 testdavy.azurecr.io/webimage:v1
        docker push testdavy.azurecr.io/webimage:v1

         
